spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codinggo?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: dhfkzmf # whitekid07
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # create, update, validate, none ?? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: your-256-bit-secret-key-change-this-in-production-please-make-it-long-enough
    access-token-expiration: 3600000    # 1시간 (밀리초)
    refresh-token-expiration: 604800000 # 7일 (밀리초)



      # redis:
    # host: localhost
    # port: 3306 # 6379

  # boot:
    # docker:
      # compose:
        # enabled: false  # Docker Compose ?? ? ?

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

# management:
  # endpoints:
    # web:
      # exposure:
        # include: "*"  # ?? Actuator ????? ??
